# Generated by Django 5.0.2 on 2024-04-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=200)),
                ('estadoCarrito', models.BooleanField(default=False)),
            ],
        ),
    ]
