# Generated by Django 5.0.2 on 2024-05-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='estadoCarrito',
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
